MODEL:
  input_shape :  [48, 48, 3]
  encodings_len: 256
  mode : 'triplet'
  distance_type : 'l1'
  backbone_name : 'efficientnet-b1'
  backbone_weights : 'noisy-student'
  freeze_backbone : False
  embeddings_normalization: True

DATALOADER:
  dataset_path : '/home/rauf/datasets/RTSD/'
  train_csv_file : '/home/rauf/datasets/RTSD/split_1/train.csv'
  val_csv_file : '/home/rauf/datasets/RTSD/split_1/val.csv'
  image_id_column : 'file_path'
  label_column : 'class_name'
  validate : True
  val_ratio : 0.2
  
GENERATOR:
  negatives_selection_mode : 'semihard'
  k_classes: 20
  k_samples: 3
  margin: 0.5
  batch_size : 8
  n_batches : 500
  augmentations : 'none'

TRAIN:
  # optimizer parameters
  optimizer : 'radam'
  learning_rate : 0.001
  decay_factor : 0.1
  step_size : 5

  # embeddings learning training parameters
  n_epochs : 1000
  
  # plot training history
  plot_history : True

# SOFTMAX_PRETRAINING:
#   # softmax pretraining parameters
#   optimizer : 'radam'
#   learning_rate : 0.02
#   decay_factor : 0.1
#   step_size : 5

#   batch_size : 16
#   val_steps : 100
#   steps_per_epoch : 500
#   n_epochs : 5

ENCODINGS:
  # encodings parameters
  save_encodings : True
  centers_only: False
  max_num_samples_of_each_class : 30
  knn_k : 1

GENERAL:
  project_name : 'road_signs_efnb1'
  work_dir : 'work_dirs/'
  tensorboard_callback: False
  wandb_callback: False